### ISSUE TITLE
SimpleSponge is confused for SpongeForge

### ISSUE THREAD

**Issue by Mohron** [simon816/SpongeBootstrap#10]
[Simple Sponge](https://minecraft.curseforge.com/projects/simple-sponge?gameCategorySlug=mc-mods&projectID=269141)'s jar name is picked up by SpongeBootstrap as a possible Sponge version. 

I discovered this when setting up a Project Ozone Lite server which contains `SimpleSponge-1.10.2-1.4.jar`. Of course, I could just rename the file but it would be nice to not have this mod confused since it exists and may be used in other packs.

**Comment by ProsperCraft** [comment]
Same problem.  This breaks automated reboots, please fix.

[19:11:24] [main/INFO]: Found launch wrapper, continuing
Multiple sponge jars have been detected, please choose
0: /opt/atm3.sponge/mods/SimpleSponge-1.12-3.5.jar


Please include an exclusion for SimpleSponge*

**Comment by Mohron** [comment]
@ProsperCraft for now just rename the file. I just made it SimpleSp0nge... lol

Hope this is fixed soon!

**Comment by ProsperCraft** [comment]
That is what I did, I renamed it to SimpleS

**Comment by simon816** [comment]
Since this is an issue for a few people (including https://github.com/simon816/SpongeBootstrap/issues/9#issuecomment-320459887), I've changed the detection to search for 'spongeforge' instead of just 'sponge'
