### ISSUE TITLE
Unable to load after update to 1.12.1 - There is a binary discrepancy between the expected input class b$1 (b$1) and the actual class.

### ISSUE THREAD

**Issue by ProsperCraft** [simon816/SpongeBootstrap#11]
Do we need a new version for 1.12.1?

https://gist.github.com/ProsperCraft/6d0631fe8f73a237ea7fb0420551b8a0

[main/FATAL] [FML]: There is a binary discrepancy between the expected input class b$1 (b$1) and the actual class. Checksum on disk is 44e36e75, in patch 51416ed6. Things are probably about to go very wrong. Did you put something into the jar file?
[00:59:27] [main/FATAL] [FML]: The game is going to exit, because this is a critical error, and it is very improbable that the modded game will work, please obtain clean jar files.

**Comment by ProsperCraft** [comment]
Nevermind, is apparently not required with the latest builds of AE2

**Comment by simon816** [comment]
I don't think this error is related to the bootstrap. Looks to me as though your forge jar is corrupted, should not be an issue on a fresh install. Re-download forge if it's still happening.

**Comment by ProsperCraft** [comment]
That is what I read as well, so I had tried that.
