### ISSUE TITLE
SpongeBootstrap can't load forge afterwards

### ISSUE THREAD

**Issue by Kirin92** [simon816/SpongeBootstrap#15]
Hey~

I use a Minecraft forge 1.12.2. server from Zap-Hosting and installed sponge.
Now I wanted to insert a mod called movingworld for davincis vessels.
On the github from movingworld I got here because the older version of Mixin was used and loaded first instead of sponge.
Now I followed the instructions for SpongeBootstrap and I asked a supporter on Zap-Hosting to change the startup to the bootstrap. Unfortunatly it said it couldn't find the forge.jar but it was there! I renamed the forge.jar to the version it had but same problem. Any ideas?

This was the startup:
java -server -Xmx4096M -Xms512M -XX:MaxPermSize=512m  -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Djline.terminal=jline.UnsupportedTerminal -jar forge.jar nogui

and changed it to:
java -server -Xmx4096M -Xms512M -XX:MaxPermSize=512m  -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Djline.terminal=jline.UnsupportedTerminal -jar SpongeBootstrap0.7.0-.jar

**Comment by simon816** [comment]
The forge jar filename should be the same as the original name as found on https://files.minecraftforge.net/.
e.g. the currently recommended forge version `1.12.2 - 14.23.5.2768` would be `forge-1.12.2-14.23.5.2768-universal.jar`

**Comment by Kirin92** [comment]
I did that.
> I renamed the forge.jar to the version it had but same problem.

**Comment by simon816** [comment]
Is the spongebootstrap jar and the forge jar in the same directory?

**Comment by Kirin92** [comment]
Yeah it was. That's why I don't know why it doesn't work. Maybe because of the server itself from zap-hosting?
Or maybe because I wrote  -jar SpongeBootstrap0.7.0-.jar
Instead of  -jar SpongeBootstrap0.7.0-.jar nogui

**Comment by simon816** [comment]
That shouldn't be a problem. I'm unsure why it's not working. One thing you can try is to go back to launching forge as before but rename the sponge jar to `_asponge....` so the jar is loaded first by forge and see if movingworld works after that.

**Comment by Kirin92** [comment]
Oh! Okay I'll try it out! If it works I'll let you know!

**Comment by Kirin92** [comment]
OMG Yes! The server started and moving world and davincis vessels works fine! Thank you so much!
