### ISSUE TITLE
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.platform.MixinPlatformAgentFML

### ISSUE THREAD

**Issue by CatMe0w** [simon816/SpongeBootstrap#16]
Tested SpongeForge versions: 1.12.2-2838-7.1.9 and 1.12.2-2838-7.1.10-RC3992
Tested Forge versions: 14.23.5.2847 and 14.23.5.2838

Full logs: https://pastebin.com/dRKD0bFv

**Comment by simon816** [comment]
Can confirm. Likely to be due to the update to Mixin 0.8.

**Comment by simon816** [comment]
Should be fixed in [0.7.1](https://github.com/simon816/SpongeBootstrap/releases/tag/v0.7.1)
