### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by Siriuo** [simon816/SpongeBootstrap#2]
Seem to be having random crashes with the below. This happens at random points while the server is running.

bash: line 1: 2731 Killed java -Xmx5G -Xms5G -XX:PermSize=768m -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -jar SpongeBootstrap-0.2.0.jar nogui

**Comment by simon816** [comment]
Could I see an example crash log? I've no idea what the issue could be without seeing what went wrong

**Comment by Siriuo** [comment]
That is the whole crash log. Server is running fine then suddenly crashes with that message. It then reboots because of the start script we have. No forge crash log is generated either.

**Comment by simon816** [comment]
All that message shows is the command line arguments used to launch the server.
Are there no reports in the `crash-reports` folder? What about `logs/fml-server-*.log` perhaps you could post a link to the FML server log so I can investigate further.

**Comment by Siriuo** [comment]
I will have to get back to you on that one. Nothing appears in the `crash-reports` or in console just before the crash.

Just looked through previous log files and cant find the specific message in the logs.

I will keep an eye on it and get some more information if this happens again.
