### ISSUE TITLE
Bootup error

### ISSUE THREAD

**Issue by Mceonith** [simon816/SpongeBootstrap#9]
I've tried running mc server 1.12 1st without bootstrap and failed to start, with bootstrap i get this 
![untitled](https://user-images.githubusercontent.com/3062613/28958895-31499f40-78c6-11e7-8501-4d78383fdf1b.png)

**Comment by Mceonith** [comment]
was with simple batch file as below 
@Echo off
java -jar -Xms1G -Xmx4G SpongeBootstrap-0.4.0.jar nogui
pause

**Comment by simon816** [comment]
This seems similar to #8, as I suggested there, check that `libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar` exists

**Comment by Mceonith** [comment]
its now 5.0.3 not 4.6
Forge runs fine if I don't add in sponge / spongebootstrap

**Comment by simon816** [comment]
Oh that would explain it, I tested the 1.12 update with an older forge (14.21.1.2397)

I will update the bootstrap

**Comment by Mceonith** [comment]
thanks and will see then what happens. please let me know when you get a chance to update. I usually have discord running as well and name on there is Mceonith as well

**Comment by Mceonith** [comment]
just for the heck of it, i added the 4.6 as well.. and then started server. this came up as the mod pack i use has a mod called simple sponge
![untitled](https://user-images.githubusercontent.com/3062613/28997552-9302e80c-79e5-11e7-883f-c9b53b243207.jpg)

https://mods.curse.com/mc-mods/minecraft/269141-simple-sponge

**Comment by simon816** [comment]
Should be fixed now with version 0.5.0

The detection is simply matching strings so that's why it's showing.
Type '1' then press enter to choose the spongeforge jar. You could rename the SimpleSponge mod jar if it's annoying

**Comment by Mceonith** [comment]
i will try it and see... Im trying to get a server going for someone else using ATM3 pack (all the mods 3) so if i change the name of simplesponge will it effect anyone that is trying to connect to the server with the atm3 modpack that they already have?

**Comment by simon816** [comment]
No, the filename is just for your convenience. (you could have all mods named a.jar b.jar ...)
Forge will just load all *.jar files

**Comment by Mceonith** [comment]
okay ... thanks and will let you know how it goes after... fingers crossed lol

**Comment by Mceonith** [comment]
as far as bootstrap all works well, ty for the help
